export const TANAKH_BOOKS = [
  // Torah (5)
  { name: "Genesis", hebrew: "בְּרֵאשִׁית", hebrewName: "Bereshit", chapters: 50, section: "Torah" },
  { name: "Exodus", hebrew: "שְׁמוֹת", hebrewName: "Shemot", chapters: 40, section: "Torah" },
  { name: "Leviticus", hebrew: "וַיִּקְרָא", hebrewName: "Vayikra", chapters: 27, section: "Torah" },
  { name: "Numbers", hebrew: "בְּמִדְבַּר", hebrewName: "Bamidbar", chapters: 36, section: "Torah" },
  { name: "Deuteronomy", hebrew: "דְּבָרִים", hebrewName: "Devarim", chapters: 34, section: "Torah" },

  // Nevi'im / Prophets
  { name: "Joshua", hebrew: "יְהוֹשֻׁעַ", hebrewName: "Yehoshua", chapters: 24, section: "Nevi'im" },
  { name: "Judges", hebrew: "שׁוֹפְטִים", hebrewName: "Shoftim", chapters: 21, section: "Nevi'im" },
  { name: "1 Samuel", hebrew: "שְׁמוּאֵל א׳", hebrewName: "Shmuel Aleph", chapters: 31, section: "Nevi'im" },
  { name: "2 Samuel", hebrew: "שְׁמוּאֵל ב׳", hebrewName: "Shmuel Bet", chapters: 24, section: "Nevi'im" },
  { name: "1 Kings", hebrew: "מְלָכִים א׳", hebrewName: "Melakhim Aleph", chapters: 22, section: "Nevi'im" },
  { name: "2 Kings", hebrew: "מְלָכִים ב׳", hebrewName: "Melakhim Bet", chapters: 25, section: "Nevi'im" },
  { name: "Isaiah", hebrew: "יְשַׁעְיָהוּ", hebrewName: "Yeshayahu", chapters: 66, section: "Nevi'im" },
  { name: "Jeremiah", hebrew: "יִרְמְיָהוּ", hebrewName: "Yirmeyahu", chapters: 52, section: "Nevi'im" },
  { name: "Ezekiel", hebrew: "יְחֶזְקֵאל", hebrewName: "Yechezkel", chapters: 48, section: "Nevi'im" },
  { name: "Hosea", hebrew: "הוֹשֵׁעַ", hebrewName: "Hoshea", chapters: 14, section: "Nevi'im" },
  { name: "Joel", hebrew: "יוֹאֵל", hebrewName: "Yoel", chapters: 4, section: "Nevi'im" },
  { name: "Amos", hebrew: "עָמוֹס", hebrewName: "Amos", chapters: 9, section: "Nevi'im" },
  { name: "Obadiah", hebrew: "עֹבַדְיָה", hebrewName: "Ovadyah", chapters: 1, section: "Nevi'im" },
  { name: "Jonah", hebrew: "יוֹנָה", hebrewName: "Yonah", chapters: 4, section: "Nevi'im" },
  { name: "Micah", hebrew: "מִיכָה", hebrewName: "Mikhah", chapters: 7, section: "Nevi'im" },
  { name: "Nahum", hebrew: "נַחוּם", hebrewName: "Nachum", chapters: 3, section: "Nevi'im" },
  { name: "Habakkuk", hebrew: "חֲבַקּוּק", hebrewName: "Chavakuk", chapters: 3, section: "Nevi'im" },
  { name: "Zephaniah", hebrew: "צְפַנְיָה", hebrewName: "Tzefanyah", chapters: 3, section: "Nevi'im" },
  { name: "Haggai", hebrew: "חַגַּי", hebrewName: "Chaggai", chapters: 2, section: "Nevi'im" },
  { name: "Zechariah", hebrew: "זְכַרְיָה", hebrewName: "Zekharyah", chapters: 14, section: "Nevi'im" },
  { name: "Malachi", hebrew: "מַלְאָכִי", hebrewName: "Malakhi", chapters: 3, section: "Nevi'im" },

  // Ketuvim / Writings
  { name: "Psalms", hebrew: "תְּהִלִּים", hebrewName: "Tehillim", chapters: 150, section: "Ketuvim" },
  { name: "Proverbs", hebrew: "מִשְׁלֵי", hebrewName: "Mishlei", chapters: 31, section: "Ketuvim" },
  { name: "Job", hebrew: "אִיּוֹב", hebrewName: "Iyyov", chapters: 42, section: "Ketuvim" },
  { name: "Song of Songs", hebrew: "שִׁיר הַשִּׁירִים", hebrewName: "Shir HaShirim", chapters: 8, section: "Ketuvim" },
  { name: "Ruth", hebrew: "רוּת", hebrewName: "Rut", chapters: 4, section: "Ketuvim" },
  { name: "Lamentations", hebrew: "אֵיכָה", hebrewName: "Eikhah", chapters: 5, section: "Ketuvim" },
  { name: "Ecclesiastes", hebrew: "קֹהֶלֶת", hebrewName: "Kohelet", chapters: 12, section: "Ketuvim" },
  { name: "Esther", hebrew: "אֶסְתֵּר", hebrewName: "Ester", chapters: 10, section: "Ketuvim" },
  { name: "Daniel", hebrew: "דָּנִיֵּאל", hebrewName: "Daniel", chapters: 12, section: "Ketuvim" },
  { name: "Ezra", hebrew: "עֶזְרָא", hebrewName: "Ezra", chapters: 10, section: "Ketuvim" },
  { name: "Nehemiah", hebrew: "נְחֶמְיָה", hebrewName: "Nechemyah", chapters: 13, section: "Ketuvim" },
  { name: "1 Chronicles", hebrew: "דִּבְרֵי הַיָּמִים א׳", hebrewName: "Divrei HaYamim Aleph", chapters: 29, section: "Ketuvim" },
  { name: "2 Chronicles", hebrew: "דִּבְרֵי הַיָּמִים ב׳", hebrewName: "Divrei HaYamim Bet", chapters: 36, section: "Ketuvim" },
];
