// Genesis 1 - Hebrew text with word-by-word pictograph breakdown
// Each word: { heb, trans, eng, letters: [{pic, phoen, heb, name}] }

export const genesis1 = [
  {
    verse: 1,
    ref: "Genesis 1:1",
    kjv: "In the beginning God created the heaven and the earth.",
    words: [
      { heb:"בְּרֵאשִׁית", trans:"bereshit", eng:"in the beginning",
        letters:[{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"בָּרָא", trans:"bara", eng:"created",
        letters:[{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"אֵת", trans:"et", eng:"(direct object marker)",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"הַשָּׁמַיִם", trans:"hashamayim", eng:"the heaven",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"וְאֵת", trans:"v'et", eng:"and",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"הָאָרֶץ", trans:"ha'aretz", eng:"the earth",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
    ]
  },
  {
    verse: 2,
    ref: "Genesis 1:2",
    kjv: "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.",
    words: [
      { heb:"וְהָאָרֶץ", trans:"v'ha'aretz", eng:"and the earth",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"הָיְתָה", trans:"hayetah", eng:"was",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"},{p:"👐",ph:"𐤄",h:"ה",n:"He"}]},
      { heb:"תֹהוּ", trans:"tohu", eng:"without form",
        letters:[{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"}]},
      { heb:"וָבֹהוּ", trans:"vavohu", eng:"and void",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"}]},
      { heb:"וְחֹשֶׁךְ", trans:"v'choshekh", eng:"and darkness",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🧱",ph:"𐤇",h:"ח",n:"Chet"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"}]},
      { heb:"עַל", trans:"al", eng:"upon",
        letters:[{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"}]},
      { heb:"פְּנֵי", trans:"penei", eng:"the face of",
        letters:[{p:"💬",ph:"𐤐",h:"פ",n:"Pe"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"תְהוֹם", trans:"tehom", eng:"the deep",
        letters:[{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"וְרוּחַ", trans:"v'ruach", eng:"and the Spirit",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🧱",ph:"𐤇",h:"ח",n:"Chet"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"of God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"מְרַחֶפֶת", trans:"merachefet", eng:"moved",
        letters:[{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🧱",ph:"𐤇",h:"ח",n:"Chet"},{p:"💬",ph:"𐤐",h:"פ",n:"Pe"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"עַל", trans:"al", eng:"upon",
        letters:[{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"}]},
      { heb:"פְּנֵי", trans:"penei", eng:"the face of",
        letters:[{p:"💬",ph:"𐤐",h:"פ",n:"Pe"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"הַמָּיִם", trans:"hamayim", eng:"the waters",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
    ]
  },
  {
    verse: 3,
    ref: "Genesis 1:3",
    kjv: "And God said, Let there be light: and there was light.",
    words: [
      { heb:"וַיֹּאמֶר", trans:"vayomer", eng:"and said",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"יְהִי", trans:"yehi", eng:"let there be",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"אוֹר", trans:"or", eng:"light",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"וַיְהִי", trans:"vayehi", eng:"and there was",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"אוֹר", trans:"or", eng:"light",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
    ]
  },
  {
    verse: 4,
    ref: "Genesis 1:4",
    kjv: "And God saw the light, that it was good: and God divided the light from the darkness.",
    words: [
      { heb:"וַיַּרְא", trans:"vayar", eng:"and saw",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"אֶת", trans:"et", eng:"(object marker)",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"הָאוֹר", trans:"ha'or", eng:"the light",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"כִּי", trans:"ki", eng:"that",
        letters:[{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"טוֹב", trans:"tov", eng:"good",
        letters:[{p:"🐍",ph:"𐤈",h:"ט",n:"Tet"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"}]},
      { heb:"וַיַּבְדֵּל", trans:"vayavdel", eng:"and divided",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"בֵּין", trans:"bein", eng:"between",
        letters:[{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"}]},
      { heb:"הָאוֹר", trans:"ha'or", eng:"the light",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"וּבֵין", trans:"uvein", eng:"and between",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"}]},
      { heb:"הַחֹשֶׁךְ", trans:"hachoshekh", eng:"the darkness",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🧱",ph:"𐤇",h:"ח",n:"Chet"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"}]},
    ]
  },
  {
    verse: 5,
    ref: "Genesis 1:5",
    kjv: "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.",
    words: [
      { heb:"וַיִּקְרָא", trans:"vayiqra", eng:"and called",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"לָאוֹר", trans:"la'or", eng:"the light",
        letters:[{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"יוֹם", trans:"yom", eng:"Day",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"וְלַחֹשֶׁךְ", trans:"v'lachoshekh", eng:"and the darkness",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🧱",ph:"𐤇",h:"ח",n:"Chet"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"}]},
      { heb:"קָרָא", trans:"qara", eng:"called",
        letters:[{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"לַיְלָה", trans:"laylah", eng:"Night",
        letters:[{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"}]},
      { heb:"וַיְהִי", trans:"vayehi", eng:"and was",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"עֶרֶב", trans:"erev", eng:"evening",
        letters:[{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"}]},
      { heb:"וַיְהִי", trans:"vayehi", eng:"and was",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"בֹקֶר", trans:"boqer", eng:"morning",
        letters:[{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"יוֹם", trans:"yom", eng:"day",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"אֶחָד", trans:"echad", eng:"first",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🧱",ph:"𐤇",h:"ח",n:"Chet"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"}]},
    ]
  },
  {
    verse: 6,
    ref: "Genesis 1:6",
    kjv: "And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.",
    words: [
      { heb:"וַיֹּאמֶר", trans:"vayomer", eng:"and said",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"יְהִי", trans:"yehi", eng:"let there be",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"רָקִיעַ", trans:"raqia", eng:"a firmament",
        letters:[{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"}]},
      { heb:"בְּתוֹךְ", trans:"betokh", eng:"in the midst of",
        letters:[{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"}]},
      { heb:"הַמָּיִם", trans:"hamayim", eng:"the waters",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
    ]
  },
  {
    verse: 7,
    ref: "Genesis 1:7",
    kjv: "And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.",
    words: [
      { heb:"וַיַּעַשׂ", trans:"vayaas", eng:"and made",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"אֶת", trans:"et", eng:"(object marker)",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"הָרָקִיעַ", trans:"haraqia", eng:"the firmament",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"}]},
      { heb:"וַיַּבְדֵּל", trans:"vayavdel", eng:"and divided",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"}]},
      { heb:"בֵּין", trans:"bein", eng:"between",
        letters:[{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"}]},
      { heb:"הַמַּיִם", trans:"hamayim", eng:"the waters",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
    ]
  },
  {
    verse: 8,
    ref: "Genesis 1:8",
    kjv: "And God called the firmament Heaven. And the evening and the morning were the second day.",
    words: [
      { heb:"וַיִּקְרָא", trans:"vayiqra", eng:"and called",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"לָרָקִיעַ", trans:"laraqia", eng:"the firmament",
        letters:[{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"}]},
      { heb:"שָׁמַיִם", trans:"shamayim", eng:"Heaven",
        letters:[{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"וַיְהִי", trans:"vayehi", eng:"and was",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"עֶרֶב", trans:"erev", eng:"evening",
        letters:[{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"}]},
      { heb:"יוֹם", trans:"yom", eng:"day",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"שֵׁנִי", trans:"sheni", eng:"second",
        letters:[{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
    ]
  },
  {
    verse: 9,
    ref: "Genesis 1:9",
    kjv: "And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so.",
    words: [
      { heb:"וַיֹּאמֶר", trans:"vayomer", eng:"and said",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"יִקָּווּ", trans:"yiqavu", eng:"let be gathered",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"}]},
      { heb:"הַמַּיִם", trans:"hamayim", eng:"the waters",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"אֶל", trans:"el", eng:"unto",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"}]},
      { heb:"מָקוֹם", trans:"maqom", eng:"place",
        letters:[{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"אֶחָד", trans:"echad", eng:"one",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🧱",ph:"𐤇",h:"ח",n:"Chet"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"}]},
      { heb:"וְתֵרָאֶה", trans:"v'teraeh", eng:"and appear",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"👐",ph:"𐤄",h:"ה",n:"He"}]},
      { heb:"הַיַּבָּשָׁה", trans:"hayabbashah", eng:"the dry land",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"👐",ph:"𐤄",h:"ה",n:"He"}]},
    ]
  },
  {
    verse: 10,
    ref: "Genesis 1:10",
    kjv: "And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.",
    words: [
      { heb:"וַיִּקְרָא", trans:"vayiqra", eng:"and called",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"לַיַּבָּשָׁה", trans:"layabbashah", eng:"the dry land",
        letters:[{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"👐",ph:"𐤄",h:"ה",n:"He"}]},
      { heb:"אֶרֶץ", trans:"eretz", eng:"Earth",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"וּלְמִקְוֵה", trans:"ulemikveh", eng:"and the gathering",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👐",ph:"𐤄",h:"ה",n:"He"}]},
      { heb:"הַמַּיִם", trans:"hamayim", eng:"of the waters",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"יַמִּים", trans:"yamim", eng:"Seas",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"טוֹב", trans:"tov", eng:"good",
        letters:[{p:"🐍",ph:"𐤈",h:"ט",n:"Tet"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"}]},
    ]
  },
  {
    verse: 11,
    ref: "Genesis 1:11",
    kjv: "And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so.",
    words: [
      { heb:"וַיֹּאמֶר", trans:"vayomer", eng:"and said",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"תַּדְשֵׁא", trans:"tadshe", eng:"bring forth",
        letters:[{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"הָאָרֶץ", trans:"ha'aretz", eng:"the earth",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"דֶּשֶׁא", trans:"deshe", eng:"grass",
        letters:[{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"עֵשֶׂב", trans:"esev", eng:"herb",
        letters:[{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"}]},
      { heb:"זֶרַע", trans:"zera", eng:"seed",
        letters:[{p:"⚔️",ph:"𐤆",h:"ז",n:"Zayin"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"}]},
      { heb:"עֵץ", trans:"etz", eng:"tree",
        letters:[{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"פְּרִי", trans:"peri", eng:"fruit",
        letters:[{p:"💬",ph:"𐤐",h:"פ",n:"Pe"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
    ]
  },
  {
    verse: 12,
    ref: "Genesis 1:12",
    kjv: "And the earth brought forth grass, and herb yielding seed after his kind, and the tree yielding fruit, whose seed was in itself, after his kind: and God saw that it was good.",
    words: [
      { heb:"וַתּוֹצֵא", trans:"vatotze", eng:"and brought forth",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🌵",ph:"𐤎",h:"ס",n:"Samech"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"הָאָרֶץ", trans:"ha'aretz", eng:"the earth",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"דֶּשֶׁא", trans:"deshe", eng:"grass",
        letters:[{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"טוֹב", trans:"tov", eng:"good",
        letters:[{p:"🐍",ph:"𐤈",h:"ט",n:"Tet"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"}]},
    ]
  },
  {
    verse: 13,
    ref: "Genesis 1:13",
    kjv: "And the evening and the morning were the third day.",
    words: [
      { heb:"וַיְהִי", trans:"vayehi", eng:"and was",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
      { heb:"עֶרֶב", trans:"erev", eng:"evening",
        letters:[{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"}]},
      { heb:"בֹקֶר", trans:"boqer", eng:"morning",
        letters:[{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"יוֹם", trans:"yom", eng:"day",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"שְׁלִישִׁי", trans:"shelishi", eng:"third",
        letters:[{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
    ]
  },
  {
    verse: 14,
    ref: "Genesis 1:14",
    kjv: "And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years.",
    words: [
      { heb:"וַיֹּאמֶר", trans:"vayomer", eng:"and said",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"מְאֹרֹת", trans:"meorot", eng:"lights",
        letters:[{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"לְאֹתֹת", trans:"le'otot", eng:"for signs",
        letters:[{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"וּלְמוֹעֲדִים", trans:"ulemoedim", eng:"and for seasons",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"שָׁנִים", trans:"shanim", eng:"and years",
        letters:[{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
    ]
  },
  {
    verse: 16,
    ref: "Genesis 1:16",
    kjv: "And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also.",
    words: [
      { heb:"וַיַּעַשׂ", trans:"vayaas", eng:"and made",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"הַמָּאוֹר", trans:"hama'or", eng:"the light",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"הַגָּדֹל", trans:"hagadol", eng:"the greater",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🐪",ph:"𐤂",h:"ג",n:"Gimel"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"}]},
      { heb:"הַכּוֹכָבִים", trans:"hakochavim", eng:"the stars",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
    ]
  },
  {
    verse: 20,
    ref: "Genesis 1:20",
    kjv: "And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth.",
    words: [
      { heb:"וַיֹּאמֶר", trans:"vayomer", eng:"and said",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"יִשְׁרְצוּ", trans:"yishretzu", eng:"bring forth abundantly",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🎣",ph:"𐤑",h:"צ",n:"Tsade"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"}]},
      { heb:"הַמַּיִם", trans:"hamayim", eng:"the waters",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"נֶפֶשׁ", trans:"nefesh", eng:"creature / soul",
        letters:[{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"},{p:"💬",ph:"𐤐",h:"פ",n:"Pe"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"}]},
      { heb:"חַיָּה", trans:"chayah", eng:"living",
        letters:[{p:"🧱",ph:"𐤇",h:"ח",n:"Chet"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👐",ph:"𐤄",h:"ה",n:"He"}]},
    ]
  },
  {
    verse: 26,
    ref: "Genesis 1:26",
    kjv: "And God said, Let us make man in our image, after our likeness.",
    words: [
      { heb:"וַיֹּאמֶר", trans:"vayomer", eng:"and said",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"נַעֲשֶׂה", trans:"naaseh", eng:"let us make",
        letters:[{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"},{p:"👁️",ph:"𐤏",h:"ע",n:"Ayin"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"👐",ph:"𐤄",h:"ה",n:"He"}]},
      { heb:"אָדָם", trans:"adam", eng:"man",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"בְּצַלְמֵנוּ", trans:"betzalmenu", eng:"in our image",
        letters:[{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🎣",ph:"𐤑",h:"צ",n:"Tsade"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"}]},
      { heb:"כִּדְמוּתֵנוּ", trans:"kidmutenu", eng:"after our likeness",
        letters:[{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"}]},
    ]
  },
  {
    verse: 27,
    ref: "Genesis 1:27",
    kjv: "So God created man in his own image, in the image of God created he him; male and female created he them.",
    words: [
      { heb:"וַיִּבְרָא", trans:"vayivra", eng:"and created",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"אֶת", trans:"et", eng:"(object marker)",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"הָאָדָם", trans:"ha'adam", eng:"the man",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"בְּצַלְמוֹ", trans:"betzalmo", eng:"in his image",
        letters:[{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🎣",ph:"𐤑",h:"צ",n:"Tsade"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"}]},
      { heb:"זָכָר", trans:"zakhar", eng:"male",
        letters:[{p:"⚔️",ph:"𐤆",h:"ז",n:"Zayin"},{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"וּנְקֵבָה", trans:"unqevah", eng:"and female",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🐟",ph:"𐤍",h:"נ",n:"Nun"},{p:"🌅",ph:"𐤒",h:"ק",n:"Qoph"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"👐",ph:"𐤄",h:"ה",n:"He"}]},
    ]
  },
  {
    verse: 28,
    ref: "Genesis 1:28",
    kjv: "And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth.",
    words: [
      { heb:"וַיְבָרֶךְ", trans:"vayvarekh", eng:"and blessed",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"פְּרוּ", trans:"peru", eng:"be fruitful",
        letters:[{p:"💬",ph:"𐤐",h:"פ",n:"Pe"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"}]},
      { heb:"וּרְבוּ", trans:"urvu", eng:"and multiply",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"}]},
      { heb:"הָאָרֶץ", trans:"ha'aretz", eng:"the earth",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
    ]
  },
  {
    verse: 31,
    ref: "Genesis 1:31",
    kjv: "And God saw every thing that he had made, and, behold, it was very good. And the evening and the morning were the sixth day.",
    words: [
      { heb:"וַיַּרְא", trans:"vayar", eng:"and saw",
        letters:[{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"}]},
      { heb:"אֱלֹהִים", trans:"Elohim", eng:"God",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"},{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"אֶת", trans:"et", eng:"(object marker)",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"✝️",ph:"𐤕",h:"ת",n:"Tav"}]},
      { heb:"כָּל", trans:"kol", eng:"every",
        letters:[{p:"✋",ph:"𐤊",h:"כ",n:"Kaph"},{p:"🦁",ph:"𐤋",h:"ל",n:"Lamed"}]},
      { heb:"אֲשֶׁר", trans:"asher", eng:"that",
        letters:[{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"👤",ph:"𐤓",h:"ר",n:"Resh"}]},
      { heb:"טוֹב", trans:"tov", eng:"good",
        letters:[{p:"🐍",ph:"𐤈",h:"ט",n:"Tet"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🏠",ph:"𐤁",h:"ב",n:"Beth"}]},
      { heb:"מְאֹד", trans:"meod", eng:"very",
        letters:[{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"},{p:"🐂",ph:"𐤀",h:"א",n:"Aleph"},{p:"🚪",ph:"𐤃",h:"ד",n:"Dalet"}]},
      { heb:"יוֹם", trans:"yom", eng:"day",
        letters:[{p:"🤲",ph:"𐤉",h:"י",n:"Yod"},{p:"🪝",ph:"𐤅",h:"ו",n:"Vav"},{p:"🌊",ph:"𐤌",h:"מ",n:"Mem"}]},
      { heb:"הַשִּׁשִּׁי", trans:"hashishi", eng:"the sixth",
        letters:[{p:"👐",ph:"𐤄",h:"ה",n:"He"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🦷",ph:"𐤔",h:"ש",n:"Shin"},{p:"🤲",ph:"𐤉",h:"י",n:"Yod"}]},
    ]
  },
];

export default genesis1;
