#!/usr/bin/env python3
"""
Build top-500 Greek NT/LXX word list with Proto-Sinaitic letter decompositions.

Greek letters descend from Phoenician letters, which descend from Proto-Sinaitic
pictographs — the same origin as Hebrew. This maps each Greek letter back to its
ancestral pictograph meaning.

Outputs: tools/greek_top500_decomposed.json
"""

import json
import os
import unicodedata

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_FILE = os.path.join(BASE, "tools", "greek_top500_decomposed.json")

# Greek letter -> Phoenician ancestor -> pictograph meaning
# Late Greek additions (phi, chi, psi, omega) get extended pictographic meanings
GREEK_PICTOGRAPHS = {
    "α": {"name": "Alpha",   "pic": "🐂", "meaning": "ox, strength, leader",        "from": "Aleph"},
    "β": {"name": "Beta",    "pic": "🏠", "meaning": "house, family, inside",        "from": "Beth"},
    "γ": {"name": "Gamma",   "pic": "🐪", "meaning": "camel, lift, carry",           "from": "Gimel"},
    "δ": {"name": "Delta",   "pic": "🚪", "meaning": "door, pathway, enter",         "from": "Daleth"},
    "ε": {"name": "Epsilon", "pic": "🪟", "meaning": "window, breath, behold",       "from": "He"},
    "ζ": {"name": "Zeta",    "pic": "⚔️", "meaning": "weapon, cut, divide",          "from": "Zayin"},
    "η": {"name": "Eta",     "pic": "🧱", "meaning": "fence, enclosure, separate",   "from": "Heth"},
    "θ": {"name": "Theta",   "pic": "🐍", "meaning": "wheel, surround, coil",        "from": "Teth"},
    "ι": {"name": "Iota",    "pic": "🤲", "meaning": "hand, deed, work",             "from": "Yod"},
    "κ": {"name": "Kappa",   "pic": "🫳", "meaning": "palm, open, tame",             "from": "Kaph"},
    "λ": {"name": "Lambda",  "pic": "🏹", "meaning": "goad, teach, direct",          "from": "Lamed"},
    "μ": {"name": "Mu",      "pic": "🌊", "meaning": "water, chaos, mighty",         "from": "Mem"},
    "ν": {"name": "Nu",      "pic": "🐟", "meaning": "fish, life, activity",         "from": "Nun"},
    "ξ": {"name": "Xi",      "pic": "🏛️", "meaning": "prop, support, pillar",        "from": "Samekh"},
    "ο": {"name": "Omicron", "pic": "👁️", "meaning": "eye, see, perceive",           "from": "Ayin"},
    "π": {"name": "Pi",      "pic": "👄", "meaning": "mouth, speak, open",           "from": "Pe"},
    "ρ": {"name": "Rho",     "pic": "👤", "meaning": "head, chief, first",           "from": "Resh"},
    "σ": {"name": "Sigma",   "pic": "🦷", "meaning": "teeth, consume, destroy",      "from": "Shin"},
    "τ": {"name": "Tau",     "pic": "✝️", "meaning": "mark, covenant, sign",          "from": "Tav"},
    "υ": {"name": "Upsilon", "pic": "🪝", "meaning": "hook, nail, connect",          "from": "Vav"},
    "φ": {"name": "Phi",     "pic": "🔥", "meaning": "flame, spirit, breath-fire",   "from": "Pe+He"},
    "χ": {"name": "Chi",     "pic": "✖️", "meaning": "cross, choice, divide",         "from": "Kaph+He"},
    "ψ": {"name": "Psi",     "pic": "🔱", "meaning": "trident, rising, pierce",      "from": "late Greek"},
    "ω": {"name": "Omega",   "pic": "👁️", "meaning": "great eye, completion, end",   "from": "Ayin (big)"},
}

# Final sigma maps to same as sigma
GREEK_PICTOGRAPHS["ς"] = GREEK_PICTOGRAPHS["σ"]


def strip_accents(ch):
    """Return the base Greek letter (lowercase) for a character."""
    nfkd = unicodedata.normalize("NFKD", ch)
    base = "".join(c for c in nfkd if unicodedata.category(c) != "Mn")
    return base.lower()


def decompose_word(word):
    """Break a Greek word into its pictograph letters."""
    letters = []
    seen_bases = set()
    for ch in word:
        base = strip_accents(ch)
        if base in GREEK_PICTOGRAPHS:
            info = GREEK_PICTOGRAPHS[base]
            # Don't duplicate consecutive identical letters in the summary
            key = info["name"]
            letters.append({
                "name": info["name"],
                "pic": info["pic"],
                "meaning": info["meaning"],
            })
    return letters


def letter_summary(letters):
    """Build a concise summary string like the Hebrew version."""
    parts = []
    for l in letters:
        short_meaning = l["meaning"].split(",")[0].strip()
        parts.append(f"{l['name']} ({l['pic']} {short_meaning})")
    return " + ".join(parts)


# Top 500 Greek words from NT/LXX by frequency
# Format: (rank, greek_word, english_definition)
# Sources: Mounce, BDAG frequency lists, Trenchard
TOP_500 = [
    (1, "καί", "and, also, even"),
    (2, "ὁ", "the (article)"),
    (3, "αὐτός", "he, she, it, self"),
    (4, "δέ", "but, and, now"),
    (5, "ἐν", "in, among, by"),
    (6, "εἰμί", "I am, exist"),
    (7, "λέγω", "I say, speak"),
    (8, "εἰς", "into, to, for"),
    (9, "οὐ", "not"),
    (10, "σύ", "you (singular)"),
    (11, "ὅς", "who, which, that"),
    (12, "οὗτος", "this"),
    (13, "ἐγώ", "I"),
    (14, "γάρ", "for, because"),
    (15, "ἐκ", "out of, from"),
    (16, "ἐπί", "upon, on, over"),
    (17, "κύριος", "lord, master"),
    (18, "θεός", "God, god"),
    (19, "ὅτι", "that, because"),
    (20, "μή", "not (with subjunctive)"),
    (21, "πᾶς", "all, every, each"),
    (22, "Ἰησοῦς", "Jesus"),
    (23, "ποιέω", "I do, make"),
    (24, "ὅστις", "whoever, whichever"),
    (25, "γίνομαι", "I become, happen"),
    (26, "πρός", "to, toward, with"),
    (27, "μετά", "with, after"),
    (28, "ἔχω", "I have, hold"),
    (29, "ἀλλά", "but, rather"),
    (30, "τις", "someone, something"),
    (31, "διά", "through, on account of"),
    (32, "ἵνα", "in order that, so that"),
    (33, "ἀπό", "from, away from"),
    (34, "Χριστός", "Christ, anointed one"),
    (35, "ἐάν", "if, when"),
    (36, "ἄνθρωπος", "man, human being"),
    (37, "ἄν", "untranslatable particle"),
    (38, "ὡς", "as, like, when"),
    (39, "κατά", "down from, according to"),
    (40, "πατήρ", "father"),
    (41, "λόγος", "word, reason, message"),
    (42, "πνεῦμα", "spirit, wind, breath"),
    (43, "πίστις", "faith, trust, belief"),
    (44, "εἷς", "one"),
    (45, "υἱός", "son"),
    (46, "ἡμέρα", "day"),
    (47, "ὑπό", "by, under"),
    (48, "ἀδελφός", "brother"),
    (49, "περί", "about, concerning"),
    (50, "οἶδα", "I know"),
    (51, "ἑαυτοῦ", "himself, herself, itself"),
    (52, "δίδωμι", "I give"),
    (53, "ἐκεῖνος", "that, that one"),
    (54, "γῆ", "earth, land, soil"),
    (55, "μέγας", "great, large"),
    (56, "λαός", "people, nation"),
    (57, "ἀκούω", "I hear, listen"),
    (58, "ἔρχομαι", "I come, go"),
    (59, "πόλις", "city"),
    (60, "ὄνομα", "name"),
    (61, "βασιλεύς", "king"),
    (62, "ἕτερος", "other, another, different"),
    (63, "ἔργον", "work, deed"),
    (64, "δύναμις", "power, miracle, ability"),
    (65, "νόμος", "law, custom"),
    (66, "ἐξέρχομαι", "I go out, come out"),
    (67, "ἀγαπάω", "I love"),
    (68, "τίς", "who? what? which?"),
    (69, "γράφω", "I write"),
    (70, "γινώσκω", "I know, understand"),
    (71, "σάρξ", "flesh, body"),
    (72, "βασιλεία", "kingdom, reign"),
    (73, "λαμβάνω", "I take, receive"),
    (74, "ἀποκρίνομαι", "I answer, reply"),
    (75, "κόσμος", "world, universe, order"),
    (76, "δόξα", "glory, splendor, honor"),
    (77, "μαθητής", "disciple, student"),
    (78, "ζωή", "life"),
    (79, "οὐρανός", "heaven, sky"),
    (80, "ἀγάπη", "love"),
    (81, "εἰσέρχομαι", "I enter, go in"),
    (82, "θάνατος", "death"),
    (83, "ἐντολή", "commandment"),
    (84, "δοῦλος", "servant, slave"),
    (85, "ὀφθαλμός", "eye"),
    (86, "ἁμαρτία", "sin"),
    (87, "ὕδωρ", "water"),
    (88, "αἷμα", "blood"),
    (89, "δύο", "two"),
    (90, "χάρις", "grace, favor"),
    (91, "ψυχή", "soul, life, self"),
    (92, "ὁδός", "way, road, path"),
    (93, "ἀλήθεια", "truth"),
    (94, "ἐξουσία", "authority, power, right"),
    (95, "καρδία", "heart"),
    (96, "ἱερόν", "temple"),
    (97, "πρόσωπον", "face, presence"),
    (98, "ἀρχή", "beginning, ruler, authority"),
    (99, "χείρ", "hand"),
    (100, "φωνή", "voice, sound"),
    (101, "ἁμαρτωλός", "sinner, sinful"),
    (102, "ἄγγελος", "angel, messenger"),
    (103, "δικαιοσύνη", "righteousness, justice"),
    (104, "εἰρήνη", "peace"),
    (105, "πρεσβύτερος", "elder"),
    (106, "ἱερεύς", "priest"),
    (107, "ἀρχιερεύς", "high priest"),
    (108, "σημεῖον", "sign, miracle"),
    (109, "φαρισαῖος", "Pharisee"),
    (110, "ὄχλος", "crowd, multitude"),
    (111, "τόπος", "place, location"),
    (112, "γυνή", "woman, wife"),
    (113, "ἀλλήλων", "one another"),
    (114, "ζητέω", "I seek, look for"),
    (115, "θέλημα", "will, desire"),
    (116, "καιρός", "time, season, opportunity"),
    (117, "χαρά", "joy, gladness"),
    (118, "ἀνήρ", "man, husband"),
    (119, "σῶμα", "body"),
    (120, "δίκαιος", "righteous, just"),
    (121, "φῶς", "light"),
    (122, "μαρτυρία", "testimony, witness"),
    (123, "ἀποστέλλω", "I send, commission"),
    (124, "ἀπόστολος", "apostle, messenger"),
    (125, "ὥρα", "hour, time"),
    (126, "πορεύομαι", "I go, travel, journey"),
    (127, "δύναμαι", "I am able, can"),
    (128, "προφήτης", "prophet"),
    (129, "κρίσις", "judgment, decision"),
    (130, "ἁγιάζω", "I sanctify, make holy"),
    (131, "σοφία", "wisdom"),
    (132, "ἐλπίς", "hope, expectation"),
    (133, "γνῶσις", "knowledge"),
    (134, "θέλω", "I want, wish, will"),
    (135, "ἀγαθός", "good"),
    (136, "πιστεύω", "I believe, trust"),
    (137, "κρίνω", "I judge, decide"),
    (138, "ζάω", "I live"),
    (139, "βαπτίζω", "I baptize, immerse"),
    (140, "ἀφίημι", "I forgive, leave, let go"),
    (141, "καλέω", "I call, name, invite"),
    (142, "ὅλος", "whole, entire, all"),
    (143, "πρῶτος", "first"),
    (144, "ἱμάτιον", "garment, cloak"),
    (145, "μόνος", "alone, only"),
    (146, "ἅγιος", "holy, sacred"),
    (147, "ἀληθινός", "true, genuine, real"),
    (148, "τέκνον", "child, offspring"),
    (149, "κεφαλή", "head"),
    (150, "γλῶσσα", "tongue, language"),
    (151, "ἐκκλησία", "church, assembly"),
    (152, "αἰών", "age, eternity"),
    (153, "αἰώνιος", "eternal, everlasting"),
    (154, "πῦρ", "fire"),
    (155, "οἶκος", "house, home, household"),
    (156, "ἔθνος", "nation, people, Gentiles"),
    (157, "μαρτυρέω", "I testify, bear witness"),
    (158, "εὐαγγέλιον", "gospel, good news"),
    (159, "διδάσκω", "I teach"),
    (160, "πλοῖον", "boat, ship"),
    (161, "ἄρτος", "bread, loaf"),
    (162, "σωτηρία", "salvation, deliverance"),
    (163, "δαιμόνιον", "demon"),
    (164, "ὁράω", "I see, perceive"),
    (165, "γεννάω", "I beget, give birth"),
    (166, "θρόνος", "throne"),
    (167, "ἐπαγγελία", "promise"),
    (168, "μέρος", "part, portion"),
    (169, "ἀνάστασις", "resurrection, rising"),
    (170, "λίθος", "stone"),
    (171, "πρόβατον", "sheep"),
    (172, "σταυρός", "cross"),
    (173, "νεκρός", "dead"),
    (174, "κηρύσσω", "I preach, proclaim"),
    (175, "ἐπιστρέφω", "I turn, return"),
    (176, "ἄρχω", "I rule, begin"),
    (177, "δεξιός", "right (hand/side)"),
    (178, "σπέρμα", "seed, offspring"),
    (179, "ἀνίστημι", "I raise up, stand"),
    (180, "πλήρης", "full, complete"),
    (181, "πληρόω", "I fill, fulfill"),
    (182, "ἱκανός", "sufficient, worthy"),
    (183, "μέλλω", "I am about to, intend"),
    (184, "σκότος", "darkness"),
    (185, "προσεύχομαι", "I pray"),
    (186, "χρόνος", "time, period"),
    (187, "ἐρωτάω", "I ask, request"),
    (188, "κρατέω", "I seize, hold, grasp"),
    (189, "εὑρίσκω", "I find, discover"),
    (190, "φοβέω", "I fear, am afraid"),
    (191, "ὑπάρχω", "I exist, am present"),
    (192, "στόμα", "mouth"),
    (193, "πονηρός", "evil, wicked"),
    (194, "πείθω", "I persuade, trust"),
    (195, "τρεῖς", "three"),
    (196, "ἀπέρχομαι", "I depart, go away"),
    (197, "παρά", "beside, from, with"),
    (198, "οὐδείς", "no one, nothing"),
    (199, "γραφή", "scripture, writing"),
    (200, "μήτηρ", "mother"),
    (201, "καθώς", "just as, even as"),
    (202, "κάθημαι", "I sit, sit down"),
    (203, "παραβολή", "parable, comparison"),
    (204, "ἰδού", "behold! look!"),
    (205, "ἑπτά", "seven"),
    (206, "αἴρω", "I take up, lift, remove"),
    (207, "σάββατον", "Sabbath, week"),
    (208, "δώδεκα", "twelve"),
    (209, "κακός", "bad, evil"),
    (210, "μᾶλλον", "more, rather"),
    (211, "πέμπω", "I send"),
    (212, "θάλασσα", "sea, lake"),
    (213, "πρεσβεία", "embassy, delegation"),
    (214, "μένω", "I remain, stay, abide"),
    (215, "ἴδιος", "one's own, private"),
    (216, "ὄρος", "mountain, hill"),
    (217, "τρόπος", "way, manner, fashion"),
    (218, "ἑορτή", "feast, festival"),
    (219, "παραδίδωμι", "I hand over, betray"),
    (220, "εὐθύς", "immediately, straight"),
    (221, "σύν", "with, together with"),
    (222, "τοιοῦτος", "such, of such kind"),
    (223, "βάλλω", "I throw, cast"),
    (224, "δοκέω", "I think, seem, suppose"),
    (225, "ὥστε", "so that, therefore"),
    (226, "κρύπτω", "I hide, conceal"),
    (227, "ὑπάγω", "I go away, depart"),
    (228, "πάσχω", "I suffer, experience"),
    (229, "ἀποθνῄσκω", "I die"),
    (230, "ἵστημι", "I stand, set, establish"),
    (231, "τηρέω", "I keep, guard, observe"),
    (232, "φέρω", "I carry, bring, bear"),
    (233, "βλέπω", "I see, look at"),
    (234, "ζῶον", "living creature, animal"),
    (235, "σταυρόω", "I crucify"),
    (236, "συνάγω", "I gather together"),
    (237, "ἐγείρω", "I raise up, awaken"),
    (238, "χρόνος", "time, period"),
    (239, "ἀρνίον", "lamb"),
    (240, "πίνω", "I drink"),
    (241, "ἄγω", "I lead, bring, go"),
    (242, "δεῖ", "it is necessary, must"),
    (243, "ὅπου", "where"),
    (244, "δώρον", "gift, offering"),
    (245, "μακάριος", "blessed, happy"),
    (246, "διδάσκαλος", "teacher"),
    (247, "τυφλός", "blind"),
    (248, "φυλακή", "prison, guard, watch"),
    (249, "κελεύω", "I command, order"),
    (250, "ἁμαρτάνω", "I sin"),
    (251, "μαρτύριον", "testimony, proof"),
    (252, "ἐσθίω", "I eat"),
    (253, "παρακαλέω", "I encourage, exhort, comfort"),
    (254, "παρουσία", "coming, presence, arrival"),
    (255, "ὑπομονή", "endurance, patience"),
    (256, "διδαχή", "teaching, doctrine"),
    (257, "ἐπιθυμία", "desire, longing, lust"),
    (258, "κοινωνία", "fellowship, communion"),
    (259, "κλαίω", "I weep, cry"),
    (260, "μετανοέω", "I repent, change mind"),
    (261, "σπείρω", "I sow, scatter seed"),
    (262, "φρονέω", "I think, have attitude"),
    (263, "κτίσις", "creation, creature"),
    (264, "διώκω", "I pursue, persecute"),
    (265, "θλῖψις", "tribulation, affliction"),
    (266, "δικαίωμα", "righteous deed, ordinance"),
    (267, "ἀσθένεια", "weakness, illness"),
    (268, "οἰκοδομέω", "I build, edify"),
    (269, "πειράζω", "I test, tempt"),
    (270, "σωτήρ", "savior, deliverer"),
    (271, "εὐλογέω", "I bless, praise"),
    (272, "ἀπόλλυμι", "I destroy, perish, lose"),
    (273, "σοφός", "wise"),
    (274, "μυστήριον", "mystery, secret"),
    (275, "κλέπτω", "I steal"),
    (276, "παράκλησις", "encouragement, comfort"),
    (277, "σκανδαλίζω", "I cause to stumble"),
    (278, "πτωχός", "poor"),
    (279, "θύρα", "door, gate"),
    (280, "θυσία", "sacrifice, offering"),
    (281, "οἰκία", "house, household"),
    (282, "ποιμήν", "shepherd"),
    (283, "ἅμα", "together, at same time"),
    (284, "κλῆσις", "calling, vocation"),
    (285, "ἐπιστολή", "letter, epistle"),
    (286, "πέτρα", "rock, stone"),
    (287, "μισέω", "I hate"),
    (288, "πλοῦτος", "wealth, riches"),
    (289, "θυγάτηρ", "daughter"),
    (290, "λύω", "I loose, destroy, free"),
    (291, "ξένος", "stranger, foreigner"),
    (292, "γεωργός", "farmer, vineyard worker"),
    (293, "ἀναβαίνω", "I go up, ascend"),
    (294, "καταβαίνω", "I go down, descend"),
    (295, "ἀγρός", "field, countryside"),
    (296, "σπεῖρα", "cohort, band of soldiers"),
    (297, "ἔρημος", "desert, wilderness"),
    (298, "ῥῆμα", "word, saying, thing"),
    (299, "φυλή", "tribe, clan"),
    (300, "ἀμπελών", "vineyard"),
    (301, "κύκλος", "circle, ring"),
    (302, "θηρίον", "beast, wild animal"),
    (303, "κώμη", "village"),
    (304, "ποτήριον", "cup, goblet"),
    (305, "σφραγίς", "seal, signet"),
    (306, "ἐλεέω", "I have mercy, show pity"),
    (307, "ἐλεημοσύνη", "mercy, alms, charity"),
    (308, "χαρίζομαι", "I forgive, give freely"),
    (309, "σκεῦος", "vessel, instrument"),
    (310, "κλίνω", "I recline, lean, bow"),
    (311, "σπλάγχνον", "compassion, inward parts"),
    (312, "ἰσχύς", "strength, might, force"),
    (313, "παρρησία", "boldness, confidence"),
    (314, "νίκη", "victory"),
    (315, "ἀστήρ", "star"),
    (316, "σφάζω", "I slay, slaughter"),
    (317, "βρῶμα", "food"),
    (318, "δένδρον", "tree"),
    (319, "σάλπιγξ", "trumpet"),
    (320, "θεραπεύω", "I heal, serve"),
    (321, "ἱλαστήριον", "mercy seat, propitiation"),
    (322, "κοιλία", "belly, womb"),
    (323, "πύλη", "gate"),
    (324, "ὀργή", "wrath, anger"),
    (325, "ἔλεος", "mercy, compassion"),
    (326, "μνημεῖον", "tomb, memorial"),
    (327, "μισθός", "wages, reward"),
    (328, "πλανάω", "I lead astray, deceive"),
    (329, "ῥίζα", "root"),
    (330, "νύξ", "night"),
    (331, "χώρα", "country, region, land"),
    (332, "θησαυρός", "treasure, storehouse"),
    (333, "ξύλον", "wood, tree, cross"),
    (334, "ἀμήν", "amen, truly, so be it"),
    (335, "βιβλίον", "book, scroll"),
    (336, "ζηλόω", "I am zealous, jealous"),
    (337, "θεμέλιος", "foundation"),
    (338, "κλείω", "I shut, close, lock"),
    (339, "λαλέω", "I speak, say"),
    (340, "λῃστής", "robber, bandit"),
    (341, "νέος", "new, young"),
    (342, "ξηραίνω", "I dry up, wither"),
    (343, "ὀλίγος", "few, little, small"),
    (344, "παιδίον", "child, infant"),
    (345, "πρόθεσις", "purpose, plan, showbread"),
    (346, "σκηνή", "tent, tabernacle, dwelling"),
    (347, "τελέω", "I finish, complete, fulfill"),
    (348, "ὑψόω", "I lift up, exalt"),
    (349, "φανερόω", "I reveal, make known"),
    (350, "χρίω", "I anoint"),
    (351, "ψεῦδος", "lie, falsehood"),
    (352, "ὠδίν", "birth pain, labor"),
    (353, "λύχνος", "lamp, light"),
    (354, "κλῆρος", "lot, inheritance, share"),
    (355, "μνῆμα", "tomb, grave"),
    (356, "ῥομφαία", "sword"),
    (357, "ἀρνέομαι", "I deny, refuse"),
    (358, "βιβλίον", "book, scroll"),
    (359, "γαστήρ", "belly, womb"),
    (360, "δεσμός", "bond, chain, fetter"),
    (361, "ἐχθρός", "enemy, hostile"),
    (362, "ζυγός", "yoke"),
    (363, "ἧλος", "nail"),
    (364, "θεμέλιον", "foundation"),
    (365, "ἱλασμός", "propitiation, atonement"),
    (366, "κανών", "rule, standard, canon"),
    (367, "λιμός", "famine, hunger"),
    (368, "μεσίτης", "mediator"),
    (369, "νικάω", "I conquer, overcome"),
    (370, "ξενίζω", "I entertain, surprise"),
    (371, "ὀπτασία", "vision, appearance"),
    (372, "παράδεισος", "paradise, garden"),
    (373, "ῥύομαι", "I rescue, deliver"),
    (374, "στέφανος", "crown, wreath"),
    (375, "τράπεζα", "table"),
    (376, "ὑπηρέτης", "servant, attendant"),
    (377, "φθείρω", "I corrupt, destroy"),
    (378, "χιτών", "tunic, garment"),
    (379, "ψάλλω", "I sing, sing praise"),
    (380, "ὠφέλεια", "benefit, advantage"),
    (381, "ἄμωμος", "blameless, without fault"),
    (382, "βοάω", "I cry out, shout"),
    (383, "γνώμη", "opinion, purpose, intent"),
    (384, "δέσμιος", "prisoner, captive"),
    (385, "ἕκαστος", "each, every"),
    (386, "ζήτησις", "debate, controversy"),
    (387, "ἦθος", "custom, habit"),
    (388, "θώραξ", "breastplate, chest"),
    (389, "ἰάομαι", "I heal, cure"),
    (390, "κατοικέω", "I dwell, inhabit"),
    (391, "λατρεύω", "I worship, serve"),
    (392, "μάχαιρα", "sword, dagger"),
    (393, "νήπιος", "infant, immature"),
    (394, "οἰκονόμος", "steward, manager"),
    (395, "παράπτωμα", "trespass, transgression"),
    (396, "σκοτία", "darkness"),
    (397, "τύπος", "pattern, example, type"),
    (398, "ὑπακοή", "obedience"),
    (399, "φιλέω", "I love (as friend), kiss"),
    (400, "χρεία", "need, necessity"),
    (401, "ψευδοπροφήτης", "false prophet"),
    (402, "ἄβυσσος", "abyss, bottomless pit"),
    (403, "βδέλυγμα", "abomination, detestable thing"),
    (404, "γνωρίζω", "I make known, reveal"),
    (405, "δεσπότης", "master, lord, sovereign"),
    (406, "ἐλευθερία", "freedom, liberty"),
    (407, "ζέω", "I boil, am fervent"),
    (408, "ἡγέομαι", "I lead, consider, regard"),
    (409, "θάπτω", "I bury"),
    (410, "ἱκετηρία", "supplication, olive branch"),
    (411, "κατηγορέω", "I accuse"),
    (412, "λεπρός", "leper, leprous"),
    (413, "μεριμνάω", "I worry, am anxious"),
    (414, "νοέω", "I perceive, understand"),
    (415, "οἰκτιρμός", "compassion, mercy"),
    (416, "παντοκράτωρ", "almighty, all-powerful"),
    (417, "σαλπίζω", "I sound a trumpet"),
    (418, "τέρας", "wonder, omen, portent"),
    (419, "ὑπερέχω", "I surpass, excel"),
    (420, "φιλαδελφία", "brotherly love"),
    (421, "χρηστότης", "kindness, goodness"),
    (422, "ψηφίζω", "I count, calculate"),
    (423, "ἄγνοια", "ignorance"),
    (424, "βοήθεια", "help, aid"),
    (425, "γρηγορέω", "I watch, am alert"),
    (426, "δημιουργός", "creator, craftsman"),
    (427, "ἐκλέγω", "I choose, select, elect"),
    (428, "ζωοποιέω", "I give life, make alive"),
    (429, "ἡσυχία", "quietness, silence, rest"),
    (430, "θαυμάζω", "I wonder, marvel at"),
    (431, "ἱστορέω", "I visit, inquire, investigate"),
    (432, "κληρονομέω", "I inherit"),
    (433, "λειτουργία", "ministry, service, worship"),
    (434, "μεταμορφόω", "I transform, transfigure"),
    (435, "νεότης", "youth"),
    (436, "ὁμοίωμα", "likeness, image, form"),
    (437, "πανοπλία", "full armor"),
    (438, "σεισμός", "earthquake"),
    (439, "τεκμήριον", "proof, evidence"),
    (440, "ὑστέρημα", "lack, deficiency"),
    (441, "φρόνησις", "wisdom, insight, prudence"),
    (442, "χορηγέω", "I supply, provide"),
    (443, "βαθύς", "deep"),
    (444, "γραμματεύς", "scribe, clerk"),
    (445, "δεκτός", "acceptable, favorable"),
    (446, "ἔκστασις", "amazement, trance, ecstasy"),
    (447, "ζεῦγος", "pair, yoke"),
    (448, "ἡλίκος", "how great, how small"),
    (449, "θεοσέβεια", "godliness, reverence"),
    (450, "ἰχθύς", "fish"),
    (451, "κατάρα", "curse"),
    (452, "λῃστής", "robber, thief"),
    (453, "μεγαλωσύνη", "majesty, greatness"),
    (454, "νηστεύω", "I fast"),
    (455, "ὁμολογέω", "I confess, declare"),
    (456, "παιδεύω", "I train, discipline, educate"),
    (457, "σπουδή", "zeal, eagerness, haste"),
    (458, "τελειόω", "I perfect, complete, finish"),
    (459, "ὑπερβολή", "excess, surpassing greatness"),
    (460, "φωτίζω", "I illuminate, enlighten"),
    (461, "χρυσός", "gold"),
    (462, "ἄνεμος", "wind"),
    (463, "βαστάζω", "I bear, carry, endure"),
    (464, "γνησίως", "genuinely, sincerely"),
    (465, "δεῖπνον", "supper, banquet"),
    (466, "ἐλαία", "olive tree, olive"),
    (467, "ζωγρέω", "I capture alive"),
    (468, "ἥλιος", "sun"),
    (469, "θρηνέω", "I mourn, lament"),
    (470, "ἰσχυρός", "strong, mighty, powerful"),
    (471, "κοινός", "common, unclean, defiled"),
    (472, "λίμνη", "lake"),
    (473, "μεσότοιχον", "dividing wall"),
    (474, "νεφέλη", "cloud"),
    (475, "ὅπλον", "weapon, armor"),
    (476, "πληγή", "plague, blow, wound"),
    (477, "σάρκινος", "fleshly, carnal"),
    (478, "τρίβος", "path, road"),
    (479, "ὑπόδημα", "sandal, shoe"),
    (480, "φυτεύω", "I plant"),
    (481, "χωρίς", "without, apart from"),
    (482, "ψευδής", "false, lying"),
    (483, "ἀνομία", "lawlessness, wickedness"),
    (484, "βέβαιος", "firm, certain, reliable"),
    (485, "γόνυ", "knee"),
    (486, "δικαστής", "judge"),
    (487, "ἐκδικέω", "I avenge, vindicate"),
    (488, "ζύμη", "leaven, yeast"),
    (489, "ἤπιος", "gentle, kind"),
    (490, "θνητός", "mortal"),
    (491, "ἰατρός", "physician, doctor"),
    (492, "κόλπος", "bosom, lap, bay"),
    (493, "λύτρον", "ransom, redemption price"),
    (494, "μέλι", "honey"),
    (495, "νόσος", "disease, sickness"),
    (496, "ὀσφύς", "waist, loins"),
    (497, "πρᾶξις", "deed, action, practice"),
    (498, "σπονδή", "drink offering, libation"),
    (499, "τεῖχος", "wall (of a city)"),
    (500, "ὑμνέω", "I sing hymns, praise"),
]


def main():
    results = []
    seen = set()

    for rank, word, eng in TOP_500:
        # Deduplicate
        if word in seen:
            continue
        seen.add(word)

        letters = decompose_word(word)
        if not letters:
            continue

        summary = letter_summary(letters)

        results.append({
            "rank": rank,
            "grk": word,
            "eng": eng,
            "letters": letters,
            "letter_summary": summary,
        })

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"Wrote {len(results)} words to {OUT_FILE}")


if __name__ == "__main__":
    main()
